name: label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubunto-latest
    permissions: 
      issues: write
    steps:
      - name: label issues
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
