name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎨 the job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🎠 this job is now running on ${{ runner.os }} server hosted by github."
      - run: echo "✨ the name of your branch is ${{github.ref }} and your repo is ${{github.repository }}."
      - name: check out repo code
        uses: actions/checkout@v2
      - run: echo "🎆the ${{github.repository }} has been cloned to the runner."
      - run: echo "⛑ the workflow is now ready to test your code on the server."
      - name: list files in the repo
        run: |
          ls ${{github.workspace }}
      - run: echo "🦺 this job's status is {{ job.status }}."
